//this data is used in populate.js to populate MongoDB
module.exports.videos = [
    {
        "title": "Mobile Dev",
        "speakers": ["Eric Navar"],
        "semester": "Fall 2023",
        "description": 'Eric\'s 2rd coming is here and we\'re going to look at mobile dev!',
        "src":'https://ds1cu037r68vs.cloudfront.net/Software%20Design%20&&%20Maintainability%20-%20Fall%202023.mp4',//update this
    },
    {
        "title": "Offile 2FA & Web Evolution",
        "speakers": ["Param Gupta, Angel"],
        "semester": "Fall 2023",
        "description": '2 short topics in 1 meeting!',
        "src":'https://ds1cu037r68vs.cloudfront.net/Software%20Design%20&&%20Maintainability%20-%20Fall%202023.mp4',//update this
    },
    {
        "title": "Logging, Metrics, && Observability",
        "speakers": ["Blake Anderson"],
        "semester": "Fall 2023",
        "description": 'Plus a little demo of Grafana',
        "src":'https://ds1cu037r68vs.cloudfront.net/Logging,%20Metrics,%20&&%20Observability%20-%20Fall%202023.mp4',
    },
    {
        "title": "What We Wish We Knew As Freshmen",
        "speakers": ["Yonas Bahre", "Blake Anderson"],
        "semester": "Fall 2023",
        "description": 'Yonas and friends spill their knowledge on stuff that they wish they knew as freshmen',
        "src":'https://ds1cu037r68vs.cloudfront.net/What%20We%20Wish%20We%20Knew%20As%20Freshmen%20-%20Fall%202023.mp4',
    },
    {
        "title": "Software Design && Maintainability",
        "speakers": ["Blake Anderson"],
        "semester": "Fall 2023",
        "description": 'Yonas Bahre talks about software design AND maintainability?!? 🤯',
        "src":'https://ds1cu037r68vs.cloudfront.net/Software%20Design%20&&%20Maintainability%20-%20Fall%202023.mp4',
    },
    {
        "title": "Web Development Fundamentals",
        "speakers": ["Blake Anderson"],
        "semester": "Fall 2023",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Web%20Development%20Fundamentals%20-%20Fall%202023.mp4',
    },
    {
        "title": "Resumes & Interviewing",
        "speakers": ["Michael Hayworth"],
        "semester": "Fall 2023",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Resumes%20&%20Interviewing%20-%20Fall%202023.mp4',
    },
    {
        "title": "Tor Workshop",
        "speakers": ["Param Gupta"],
        "semester": "Spring 2023",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Tor%20Workshop%20-%20Spring%202023.mp4',
    },
    {
        "title": "Intro to Frontend (JS React)",
        "speakers": ["Blake Anderson"],
        "semester": "Spring 2023",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20Frontend%20(JS_React)%20-%20Spring 2023.mp4',
    },
    {
        "title": "Intro to Frontend (HTML, CSS)",
        "speakers": ["Blake Anderson"],
        "semester": "Fall 2023",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20Frontend%20(HTML_CSS)%20-%20Spring%202023.mp4',
    },
    {
        "title": "FastAPI Backends in Python",
        "speakers": ["Blake Anderson"],
        "semester": "Spring 2023",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/FastAPI%20Backends%20in%20Python%20-%20Spring 2023.mp4',
    },
    {
        "title": "Intro to Git and Version Control",
        "speakers": ["Yonas Bahre"],
        "semester": "Spring 2023",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20Git%20and%20Version%20Control%20-%20Spring%202023.mp4',
    },
    {
        "title": "Intro to Go Programming",
        "speakers": ["Yonas Bahre"],
        "semester": "Fall 2022",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20Go%20Programming%20-%20Spring%202023.mp4',
    },
    {
        "title": "SSDocumentary - A brief history of SSD",
        "speakers": ["Blake Anderson", "Eric Navar", "Ranger Chenore", "Trevor Richardson"],
        "semester": "Fall 2022",
        "description": 'A documentary of why SSD started and its history up until Fall 2022 as president Ranger Chenore and former president Eric Navar graduate',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20Software%20Development%20(Fall%20_22).mp4',
    },
    {
        "title": "Debugging",
        "speakers": ["Yonas Bahre"],
        "semester": "Fall 2022",
        "description": 'Yonas gives cool tips and tricks for debugging',
        "src":'https://ds1cu037r68vs.cloudfront.net/Debugging.mp4',
    },
    {
        "title": "Intro to JavaScript Part 2",
        "speakers": ["Eric Navar"],
        "semester": "Fall 2022",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20JavaScript%20Part%202.mp4',
    },
    {
        "title": "Intro to JavaScript Part 1",
        "speakers": ["Eric Navar", "Ranger Chenore"],
        "semester": "Fall 2022",
        "description": 'The top 1 meeting',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20JavaScript%20Part%201.mp4',
    },
    {
        "title": "Blockchain",
        "speakers": ["CJ Weir"],
        "semester": "Fall 2022",
        "description": 'Jimmy McGill, a struggling lawyer, tries to make a name for himself in the legal world, while dealing with personal and financial challenges.',
        "src":'https://ds1cu037r68vs.cloudfront.net/Blockchain%20CJ%20Weir.mp4',
    },
    {
        "title": "Intro to Software Development",
        "speakers": ["Eric Navar"],
        "semester": "Fall 2022",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20Software%20Development%20(Fall%20_22).mp4',
    },
    {
        "title": "Spring 2022 Elections and Lightning Talks",
        "speakers": ["Blake Anderson"],
        "semester": "Spring 2022",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Spring%202022%20Elections%20and%20Lightning%20Talks.mp4',
    },
    {
        "title": "Programming Languages (ft. Blake Anderson)",
        "speakers": ["Blake Anderson"],
        "semester": "Spring 2022",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Programming%20Languages%20(ft.%20Blake Anderson).mp4',
    },
    {
        "title": "Software Testing",
        "speakers": ["Eric Navar"],
        "semester": "Spring 2022",
        "description": 'A look at software testing! We focus mainly on frontend testing and do a demo of Cypress',
        "src":'https://ds1cu037r68vs.cloudfront.net/Software%20Testing.mp4',
    },
    {
        "title": "Databases & SQL",
        "speakers": ["Eric Navar", "Ranger Chenore"],
        "semester": "Fall 2021",
        "description": 'Learn about databases and SQL! We also go through a basic SQL injection demo.',
        "src":'https://ds1cu037r68vs.cloudfront.net/Databases%20and%20SQL.mp4',
    },
    {
        "title": "Gainesville Startup Panel",
        "speakers": ["Trevor Richardson"],
        "semester": "Fall 2021",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Fall%202021%20SSD%20Startup%20Panel.mp4',
    },
    {
        "title": "Networking Software in the Industry",
        "speakers": ["Trevor Richardson"],
        "semester": "Fall 2021",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Networking%20Software%20in%20the%20Industry.mp4',
    },
    {
        "title": "Frontend Development",
        "speakers": ["Eric Navar"],
        "semester": "Fall 2021",
        "description": 'Learn about the basics of making a web app with a React demo!',
        "src":'https://ds1cu037r68vs.cloudfront.net/Frontend%20Development.mp4',
    },
    {
        "title": "Adobe XD and UX Design",
        "speakers": [],
        "semester": "Fall 2022",
        "description": 'Learn about UX design and prototyping! Featuring ___ from the institute of Digital Arts at UF.',
        "src":'https://ds1cu037r68vs.cloudfront.net/Adobe%20XD%20and%20UX%20Design.mp4',
    },
    {
        "title": "Natural Language Processing with Open Source Club",
        "speakers": ["Caijun Qin"],
        "semester": "Fall 2022",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Natural%20Language%20Processing%20with%20Open%20Source%20Club.mp4',
    },
    {
        "title": "Advanced Git Workshop",
        "speakers": ["Blake Anderson"],
        "semester": "Spring 2022",
        "description": 'For people who already know the basics, here is some more advanced stuff you can do with Git',
        "src":'https://ds1cu037r68vs.cloudfront.net/Advanced%20Git%20Workshop.mp4',
    },
    {
        "title": "Beginner Git Workshop",
        "speakers": ["Eric Navar"],
        "semester": "Spring 2022",
        "description": 'The baby beginner stuff with Git',
        "src":'https://ds1cu037r68vs.cloudfront.net/Advanced%20Git%20Workshop.mp4',
    },
    {
        "title": "Intro to SSD - Software Design and Maintainability",
        "speakers": ["Blake Anderson"],
        "semester": "Spring 2022",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Intro%20to%20SSD%20-%20Software%20Design%20and%20Maintainability.mp4',
    },
    {
        "title": "Functional Programming",
        "speakers": ["Blake Anderson"],
        "semester": "Fall 2021",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Functional%20Programming.mp4',
    },
    {
        "title": "NSBP & SSD Python Libraries for Physicists",
        "speakers": ["Caijun Qin"],
        "semester": "Fall 2021",
        "description": 'Hit the griddy',
        "src":'https://ds1cu037r68vs.cloudfront.net/Natural%20Language%20Processing%20with%20Open%20Source%20Club.mp4',
    },
    {
        "title": "AMA with David Rupp - Amazon SDE",
        "speakers": ["David Rupp"],
        "semester": "Fall 2020",
        "description": 'Jimmy McGill, a struggling lawyer, tries to make a name for himself in the legal world, while dealing with personal and financial challenges.',
        "src":'https://ds1cu037r68vs.cloudfront.net/AMA%20with%20David%20Rupp%20-%20Amazon%20SDE%20[Spring%202021].mp4',
    },
]
